/**
 * Copyright (c) 2015-present, chatboard
 * All rights reserved.
 */

"use strict";

module.exports = {
    "CHTB_CLIENT_CHAT_COLOR_CHANGE": "CHTB_CLIENT_CHAT_COLOR_CHANGE",
    "CHTB_CLIENT_CHAT_ICON_CHANGE": "CHTB_CLIENT_CHAT_ICON_CHANGE",
    "CHTB_CLIENT_CHAT_ROOM_JOIN_REQUEST": "CHTB_CLIENT_CHAT_ROOM_JOIN_REQUEST",
    "CHTB_CLIENT_CHAT_TITLE_CHANGE": "CHTB_CLIENT_CHAT_TITLE_CHANGE",
    "CHTB_CLIENT_CONNECTION": "CHTB_CLIENT_CONNECTION",
    "CHTB_CLIENT_DISCONNECT": "CHTB_CLIENT_DISCONNECT",
    "CHTB_CLIENT_MESSAGE": "CHTB_CLIENT_MESSAGE",
    "CHTB_SERVER_CHAT_UPDATE": "CHTB_SERVER_CHAT_UPDATE",
    "CHTB_SERVER_MESSAGE": "CHTB_SERVER_MESSAGE",
    "CHTB_SERVER_ROOM_JOIN_APPROVE": "CHTB_SERVER_ROOM_JOIN_APPROVE"
};
